### ISSUE TITLE
Permission denied: '/app/static

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#306]
```
django_1         | Traceback (most recent call last):
django_1         |   File "manage.py", line 22, in <module>
django_1         |     main()
django_1         |   File "manage.py", line 18, in main
django_1         |     execute_from_command_line(sys.argv)
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
django_1         |     utility.execute()
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
django_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
django_1         |     self.execute(*args, **cmd_options)
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
django_1         |     output = self.handle(*args, **options)
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
django_1         |     collected = self.collect()
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
django_1         |     handler(path, prefixed_path, storage)
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 348, in copy_file
django_1         |     self.storage.save(prefixed_path, source_file)
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 54, in save
django_1         |     return self._save(name, content)
django_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 255, in _save
django_1         |     os.makedirs(direc
```

**Comment by Sispheor** [comment]
Done and merged in dev branch
