### ISSUE TITLE
When global sync tower

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#695]
```
INFO 2023-09-29 15:20:43,584 tasks [towerserver_sync] sync tower server with id: 1
celery-worker_1  | ERROR 2023-09-29 15:20:45,687 trace Task service_catalog.tasks.towerserver_sync[022320ea-2795-4982-86d9-9ef1dc4de5e0] raised unexpected: KeyError('default')
celery-worker_1  | Traceback (most recent call last):
celery-worker_1  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
celery-worker_1  |     R = retval = fun(*args, **kwargs)
celery-worker_1  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery-worker_1  |     return self.run(*args, **kwargs)
celery-worker_1  |   File "/app/service_catalog/tasks.py", line 21, in towerserver_sync
celery-worker_1  |     tower_server.sync(job_template_id)
celery-worker_1  |   File "/app/service_catalog/models/tower_server.py", line 44, in sync
celery-worker_1  |     self._update_job_template_from_tower(job_template_from_tower)
celery-worker_1  |   File "/app/service_catalog/models/tower_server.py", line 86, in _update_job_template_from_tower
celery-worker_1  |     job_template.save()
celery-worker_1  |   File "/app/service_catalog/models/job_templates.py", line 98, in save
celery-worker_1  |     operation.update_survey()
celery-worker_1  |   File "/app/service_catalog/models/operations.py", line 82, in update_survey
celery-worker_1  |     'default': field['default']
celery-worker_1  | KeyError: 'default'
```

**Comment by Sispheor** [comment]
Workaround: set a default value on integer field in the job template survey
