### ISSUE TITLE
Bug when I process a request

### ISSUE THREAD

**Issue by a-belhadj** [HewlettPackard/squest#76]
Bug appear after processing a request with the "Demo job template"
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/request/10/process/

Django Version: 3.1.7
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'fontawesome-free',
 'django_celery_results',
 'django_celery_beat',
 'guardian',
 'django_node_assets',
 'django_filters',
 'drf_yasg',
 'service_catalog',
 'resource_tracker']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/anthony/.cache/pypoetry/virtualenvs/tower-service-catalog--Kn3-9f8-py3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/anthony/.cache/pypoetry/virtualenvs/tower-service-catalog--Kn3-9f8-py3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/anthony/.cache/pypoetry/virtualenvs/tower-service-catalog--Kn3-9f8-py3.8/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/anthony/HPE/squest/service_catalog/views/admin/request.py", line 162, in admin_request_process
    target_request.perform_processing()
  File "/home/anthony/.cache/pypoetry/virtualenvs/tower-service-catalog--Kn3-9f8-py3.8/lib/python3.8/site-packages/django_fsm/__init__.py", line 520, in _change_state
    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
  File "/home/anthony/.cache/pypoetry/virtualenvs/tower-service-catalog--Kn3-9f8-py3.8/lib/python3.8/site-packages/django_fsm/__init__.py", line 326, in change_state
    result = method(instance, *args, **kwargs)
  File "/home/anthony/HPE/squest/service_catalog/models/request.py", line 105, in perform_processing
    tower_job_id = self.operation.job_template.execute(extra_vars=tower_extra_vars)
  File "/home/anthony/HPE/squest/service_catalog/models/job_templates.py", line 22, in execute
    return tower_job_run.id

Exception Type: AttributeError at /admin/request/10/process/
Exception Value: 'NoneType' object has no attribute 'id'
```

**Comment by Sispheor** [comment]
Fixed with the last release.

**Comment by Sispheor** [comment]
Are you on Squest 1.0?

**Comment by Sispheor** [comment]
In your log: :{"detail":"You do not have permission to perform this action."}

Seems that your Tower/AWX token does not provide permission to execute a job template.

**Comment by Sispheor** [comment]
Doc: https://hewlettpackard.github.io/squest/1.0/configuration/tower_settings/
