### ISSUE TITLE
Wait until Django deployment available step

### ISSUE THREAD

**Issue by Scregneugneu** [HewlettPackard/squest#794]
Hello,

During the installation of squest, I have a problem on the step "Wait until Django deployment available" : 

TASK [squest_k8s : Wait until Django deployment available] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /squest/k8s/squest_k8s/tasks/05-django.yml:354
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1724752360.2739174-37462-156424066798684 `" && echo ansible-tmp-1724752360.2739174-37462-156424066798684="` echo /root/.ansible/tmp/ansible-tmp-1724752360.2739174-37462-156424066798684 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-35540o6w4yefw/tmp8yy7be3a TO /root/.ansible/tmp/ansible-tmp-1724752360.2739174-37462-156424066798684/AnsiballZ_k8s_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1724752360.2739174-37462-156424066798684/ /root/.ansible/tmp/ansible-tmp-1724752360.2739174-37462-156424066798684/AnsiballZ_k8s_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1724752360.2739174-37462-156424066798684/AnsiballZ_k8s_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1724752360.2739174-37462-156424066798684/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_brgr8spv/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 211, in main
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_brgr8spv/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 173, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_brgr8spv/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/service.py", line 304, in find
    raise CoreException(
ansible_collections.kubernetes.core.plugins.module_utils.k8s.exceptions.CoreException: Failed to gather information about Deployment(s) even after waiting for 600 seconds
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "apps/v1",
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": null,
            "field_selectors": [],
            "host": null,
            "impersonate_groups": null,
            "impersonate_user": null,
            "kind": "Deployment",
            "kubeconfig": "/etc/rancher/k3s/k3s.yaml",
            "label_selectors": [],
            "name": "django",
            "namespace": "squest",
            "no_proxy": null,
            "password": null,
            "persist_config": null,
            "proxy": null,
            "proxy_headers": null,
            "username": null,
            "validate_certs": null,
            "wait": true,
            "wait_condition": {
                "reason": null,
                "status": true,
                "type": "Available"
            },
            "wait_sleep": 10,
            "wait_timeout": 600
        }
    },
    "msg": "Failed to gather information about Deployment(s) even after waiting for 600 seconds"
}

Did you already encountered this problem ?

**Comment by Sispheor** [comment]
Hi, sorry for the delay.
No we never encountered this issue before. Maybe the task failed but the deployment is done anyway? You can re-execute the playbook.

Note: we are going to work on a Helm based deployment soon

**Comment by Scregneugneu** [comment]
Thanks for the information :)
